[2023-01-30 22:53:33,376][tensorflow][WARNING] - AutoGraph could not transform <bound method GroupNormalization.call of <tensorflow_addons.layers.normalizations.GroupNormalization object at 0x7fc6d776e5e0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-01-30 22:53:40,155][tensorflow][WARNING] - AutoGraph could not transform <bound method Processor.mask of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fc6d44bb130>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-01-30 22:53:41,084][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-01-30 22:53:41,085][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_3'), name='input_3', description="created by layer 'input_3'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-01-30 22:53:44,141][tensorflow][WARNING] - AutoGraph could not transform <bound method CELoss.call of <losses.cross_entropy_loss_2.CELoss object at 0x7fc6dffd88e0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-01-30 22:53:55,695][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-01-30 22:53:55,696][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_3'), name='input_3', description="created by layer 'input_3'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-01-30 23:11:28,013][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-01-30 23:11:28,014][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_3'), name='input_3', description="created by layer 'input_3'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-01-31 01:46:12,892][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Activation object at 0x7fc6d76f5a60>, because it is not built.
[2023-01-31 01:46:13,474][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.pooling.AveragePooling1D object at 0x7fc6d774c2b0>, because it is not built.
[2023-01-31 01:46:49,353][absl][WARNING] - Found untraced functions such as activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, transformer_encoder_layer_call_fn while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-01-31 01:46:50,152][absl][WARNING] - Found untraced functions such as activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, transformer_encoder_layer_call_fn while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-01-31 01:47:46,196][tensorflow][INFO] - Assets written to: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_tal/6/assets
[2023-01-31 07:25:28,892][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Activation object at 0x7fc6d76f5a60>, because it is not built.
[2023-01-31 07:25:29,488][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.pooling.AveragePooling1D object at 0x7fc6d774c2b0>, because it is not built.
[2023-01-31 07:26:08,171][absl][WARNING] - Found untraced functions such as activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, transformer_encoder_layer_call_fn while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-01-31 07:26:09,082][absl][WARNING] - Found untraced functions such as activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, transformer_encoder_layer_call_fn while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-01-31 07:27:06,794][tensorflow][INFO] - Assets written to: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_tal/6/assets
